name: Java CI/CD to EC2

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate dynamic version
        id: version
        run: |
          TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "")
          if [ -z "$TAG" ]; then
            VERSION="v1.0.${{ github.run_number }}"
          else
            VERSION=$TAG
          fi
          echo "Using version: $VERSION"
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Cache Sonar packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Build with Maven
        run: mvn clean package

      - name: Rename WAR file with version
        run: |
          mv target/*.war target/Stateful-Tracker-${{ steps.version.outputs.version }}.war

      - name: List target directory
        run: ls -l target

      - name: Run SonarQube Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: mvn sonar:sonar -Dsonar.login=$SONAR_TOKEN -Dsonar.host.url=$SONAR_HOST_URL

      - name: Upload WAR file
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: target/*.war

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download WAR file
        uses: actions/download-artifact@v4
        with:
          name: java-app
          path: target

      - name: Set up SSH key and known_hosts
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Generate version for deployment
        id: version
        run: |
          VERSION="v1.0.${{ github.run_number }}"
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Deploy to Nexus
        env:
          NEXUS_URL: ${{ secrets.NEXUS_URL }}
          NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
        run: |
          mvn deploy:deploy-file \
            -Durl=${{ secrets.NEXUS_URL }} \
            -DrepositoryId=nexus-releases \
            -Dfile=target/Stateful-Tracker-${{ steps.version.outputs.version }}.war \
            -DgroupId=com.microsoft.webapp.samples \
            -DartifactId=Stateful-Tracker \
            -Dversion=${{ steps.version.outputs.version }} \
            -Dpackaging=war \
            -DgeneratePom=true \
            -Dusername=${{ secrets.NEXUS_USERNAME }} \
            -Dpassword=${{ secrets.NEXUS_PASSWORD }}

      - name: Deploy WAR via SCP to EC2
        run: |
          scp -i ~/.ssh/id_rsa target/Stateful-Tracker-${{ steps.version.outputs.version }}.war ec2-user@${{ secrets.SSH_HOST }}:/home/ec2-user/

      - name: Copy WAR to Tomcat webapps
        run: |
          ssh -i ~/.ssh/id_rsa ec2-user@${{ secrets.SSH_HOST }} 'sudo cp /home/ec2-user/Stateful-Tracker-${{ steps.version.outputs.version }}.war /opt/tomcat/webapps/'
