deploy:
  needs: build
  runs-on: ubuntu-latest
  
  steps:
    - name: Download WAR file
      uses: actions/download-artifact@v4
      with:
        name: java-app
        path: target
        
    - name: Set up SSH key and known_hosts
      run: |
        # Ensure ~/.ssh exists
        mkdir -p ~/.ssh

        # Add the private key to the SSH config
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        
        # Ensure we add EC2's host key to known_hosts to prevent SSH authenticity check failure
        echo "Adding EC2 to known_hosts..."
        ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

    - name: Deploy WAR via SCP
      run: |
        # Copy the WAR file to EC2 instance
        scp -i ~/.ssh/id_rsa target/*.war ec2-user@${{ secrets.SSH_HOST }}:/home/ec2-user/

    - name: Copy WAR file to Tomcat webapps
      run: |
        # Move the WAR file to the Tomcat webapps directory
        ssh -i ~/.ssh/id_rsa ec2-user@${{ secrets.SSH_HOST }} 'sudo cp /home/ec2-user/*.war /opt/tomcat9/webapps/'
